name = "sentinel"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# [D1 Database Binding]
[[d1_databases]]
binding = "DB"
database_name = "sentinel-db"
database_id = "4ebaa46f-3937-42fd-a315-2e8531e3e13e" # sentinel-db

# [Cron Trigger]
# Pages does not support [triggers] in wrangler.toml yet.
# Use Cloudflare Dashboard -> Functions -> Scheduled Triggers if needed.


# [Observability]
[observability]
enabled = true
